# Generated by Django 5.2.8 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatingorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Запрос на заказ', 'verbose_name_plural': 'Запросы на заказы'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'managed': False, 'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='creatingorder',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обработке'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PROCESSING', max_length=12),
        ),
    ]
