# Generated by Django 5.2.8 on 2025-11-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_creatingorder_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('contact', models.CharField(max_length=255, verbose_name='Телефон/Telegram')),
                ('item_name', models.CharField(max_length=255, verbose_name='Название товара/кейса')),
                ('category', models.CharField(choices=[('cosmetics', 'Косметика'), ('clothing', 'Одежда'), ('tech', 'Техника'), ('home', 'Дом'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('received_at', models.DateField(verbose_name='Дата получения')),
                ('completed_at', models.DateField(verbose_name='Дата завершения')),
                ('report_type', models.CharField(blank=True, choices=[('publication', 'Публикация'), ('marketplace_review', 'Отзыв на МП'), ('photo_report', 'Фото-отчёт'), ('video_report', 'Видео-отчёт'), ('other', 'Другое')], max_length=50, verbose_name='Тип отчёта')),
                ('proof_links', models.JSONField(blank=True, default=list, verbose_name='Ссылки на материалы')),
                ('proof_files', models.JSONField(blank=True, default=list, verbose_name='Загруженные файлы (пути)')),
                ('score_overall', models.IntegerField(blank=True, null=True, verbose_name='Общее впечатление (1-5)')),
                ('score_expectation_fit', models.IntegerField(blank=True, null=True, verbose_name='Соответствие ожиданиям (1-5)')),
                ('score_quality_effect', models.IntegerField(blank=True, null=True, verbose_name='Качество/эффективность (1-5)')),
                ('score_usability', models.IntegerField(blank=True, null=True, verbose_name='Удобство использования (1-5)')),
                ('score_value_for_money', models.IntegerField(blank=True, null=True, verbose_name='Соотношение цена/качество (1-5)')),
                ('score_recommend', models.IntegerField(blank=True, null=True, verbose_name='Готовность рекомендовать (0-10)')),
                ('likes', models.TextField(blank=True, verbose_name='Что понравилось?')),
                ('improvements', models.TextField(blank=True, verbose_name='Что улучшить?')),
                ('review_text', models.TextField(blank=True, max_length=1000, verbose_name='Комментарий/отзыв')),
                ('emotions_3_words', models.CharField(blank=True, max_length=255, verbose_name='3 слова-эмоции о товаре')),
                ('issues_occured', models.BooleanField(default=False, verbose_name='Опыт проблем/дефектов')),
                ('issues_note', models.TextField(blank=True, verbose_name='Описание проблем')),
                ('would_buy', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('depends_on_price', 'Зависит от цены')], max_length=50, verbose_name='Купили бы сами?')),
                ('ready_for_next', models.BooleanField(default=False, verbose_name='Готовность к повторному тесту')),
                ('consent_truthful', models.BooleanField(default=False, verbose_name='Подтверждаю достоверность данных')),
                ('consent_use_materials', models.BooleanField(default=False, verbose_name='Разрешаю использовать материалы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_report', to='orders.purchase', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отчёт о тестировании',
                'verbose_name_plural': 'Отчёты о тестировании',
                'ordering': ('-created_at',),
            },
        ),
    ]
