# Generated by Django 5.2.8 on 2025-11-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consent_truthful',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consent_use_materials',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emotions_3_words',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='issues_note',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='issues_occurred',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proof_files',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proof_links',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ready_for_next',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_expectation_fit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_overall',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_quality_effect',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_recommend',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_usability',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_value_for_money',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='would_buy',
        ),
    ]
