# Generated by Django 5.2.8 on 2025-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad_pricing',
            field=models.JSONField(blank=True, default=list, verbose_name='Стоимость рекламы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация, пожелания, ссылки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='audience_gender_age',
            field=models.TextField(blank=True, verbose_name='Пол и возраст аудитории'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='audience_region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основной регион/страна аудитории'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_reach',
            field=models.JSONField(blank=True, default=list, verbose_name='Средний охват постов/сторис/видео'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='barter_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Какие категории товаров тебе интересны для бартерных'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blog_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание блога'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blog_experience',
            field=models.CharField(blank=True, choices=[('<6months', 'До 6 месяцев'), ('6months-1year', '6 мес - 1 год'), ('1-2years', '1-2 года'), ('>2years', 'Более 2 лет')], max_length=50, verbose_name='Как давно ведёшь блог?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blog_management',
            field=models.CharField(blank=True, choices=[('myself', 'Сам(а)'), ('assistant_manager', 'Есть помощник/менеджер'), ('agency', 'Агентство')], max_length=50, verbose_name='Ты сам(а) ведёшь блог или есть команда/менеджер?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blog_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='Тематика блога'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collaboration_examples',
            field=models.JSONField(blank=True, default=list, verbose_name='Примеры успешных коллабораций'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collaboration_formats',
            field=models.JSONField(blank=True, default=list, verbose_name='Какие форматы сотрудничества тебе интересны?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_marketing_calls',
            field=models.BooleanField(default=False, verbose_name='Согласие на получение информационных и рекламных звонков'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_marketing_email',
            field=models.BooleanField(default=False, verbose_name='Согласие на получение рекламных материалов на email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_privacy',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coverage_regions',
            field=models.CharField(blank=True, max_length=500, verbose_name='Город(а)/регионы охвата'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='engagement_level',
            field=models.CharField(blank=True, max_length=255, verbose_name='Уровень вовлечённости'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('F', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_collaborations',
            field=models.BooleanField(default=False, verbose_name='Были ли у тебя уже рекламные коллаборации?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_media_kit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть ли у тебя медиа-кит?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_self_employment',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть ли у вас самозанятость?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_blog_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на основной блог'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='media_kit_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на медиа-кит'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platforms',
            field=models.JSONField(blank=True, default=list, verbose_name='Платформы, на которых ведёшь блог'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='products_wont_advertise',
            field=models.TextField(blank=True, verbose_name='Какой товар не будешь рекламировать точно?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publication_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('few_times_week', 'Несколько раз в неделю'), ('once_week', 'Раз в неделю'), ('less_often', 'Реже')], max_length=50, verbose_name='Частота публикаций'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ready_for_barter',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('depends_on_product', 'Зависит от товара/условий')], max_length=50, verbose_name='Готов(а) на бартерное сотрудничество?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ready_for_blogger_community',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('maybe', 'Возможно'), ('no', 'Нет')], max_length=50, verbose_name='Согласен(на) ли ты участвовать в закрытом сообществе блогеров?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ready_for_brand_projects',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('maybe_depends', 'Возможно, смотря на условия'), ('no', 'Нет')], max_length=50, verbose_name='Готов(а) участвовать в проектах/промо-акциях/челленджах от брендов?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ready_for_paid_ads',
            field=models.CharField(blank=True, choices=[('yes_no_problem', 'Да, без проблем'), ('depends_on_conditions', 'Зависит от условий'), ('no', 'Нет')], max_length=50, verbose_name='Готов(а) делать рекламу по договору/купленным сделкам?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ready_for_self_employment',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('maybe', 'Возможно')], max_length=50, verbose_name='Готовы ли вы оформить самозанятость?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ready_to_share_results',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('by_agreement', 'По договорённости')], max_length=50, verbose_name='Готов(а) делиться результатами'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки на все активные соцсети'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribers_by_platform',
            field=models.JSONField(blank=True, default=list, verbose_name='Количество подписчиков по платформам'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакт (телефон или Telegram)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО или псевдоним блогера'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_participating',
            field=models.BooleanField(default=False, verbose_name='Участвует в заказах'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, verbose_name='ПВЗ'),
        ),
    ]
