# Generated by Django 5.2.8 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_ad_pricing_userprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт (телефон или Telegram)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ПВЗ'),
        ),
    ]
